src/main/java/pl/codementors/finalstore/model/Order.java
package pl.codementors.finalstore.model;

import javax.persistence.*;
import java.util.List;
import java.util.Objects;

/**
 * Entity class representing an order in our store.
 */
@Entity
@Table(name = "orders")
public class Order {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @ManyToOne
    @JoinColumn(name = "customer_id", referencedColumnName = "id")
    private User customer;

    @Column
    private String adress;

    @OneToMany(mappedBy = "order", fetch = FetchType.EAGER)
    private List<Product> products;

    public Order() {
    }

    public Order(User customer, String adress, List<Product> products) {
        this.customer = customer;
        this.adress = adress;
        this.products = products;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public User getCustomer() {
        return customer;
    }

    public void setCustomer(User customer) {
        this.customer = customer;
    }

    public String getAdress() {
        return adress;
    }

    public void setAdress(String adress) {
        this.adress = adress;
    }

    public List<Product> getProducts() {
        return products;
    }

    public void setProducts(List<Product> products) {
        this.products = products;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Order order = (Order) o;
        return id == order.id &&
                Objects.equals(customer, order.customer) &&
                Objects.equals(adress, order.adress);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, customer, adress);
    }

    @Override
    public String toString() {
        return "Order{" +
                "id=" + id +
                ", customer=" + customer +
                ", adress='" + adress + '\'' +
                '}';
    }
}

src/main/java/pl/codementors/finalstore/model/Product.java
package pl.codementors.finalstore.model;


import javax.persistence.*;
import java.util.Objects;


/**
 * Entity class representing a product in our store.
 */
@Entity
@Table(name = "products")
public class Product {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @Column
    private String name;

    @Column
    private String description;

    @Column
    private int price;

    @ManyToOne
    @JoinColumn(name = "user", referencedColumnName = "id", nullable = false)
    private User seller;

    @Column(name = "availability")
    private boolean isAvailable;

    @ManyToOne
    @JoinColumn(name = "order_id", referencedColumnName = "id")
    private Order order;

    public Product() {
    }

    public Product(String name, String description, int price, User seller, boolean isAvailable) {
        this.name = name;
        this.description = description;
        this.price = price;
        this.seller = seller;
        this.isAvailable = isAvailable;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getPrice() {
        return price;
    }

    public void setPrice(int price) {
        this.price = price;
    }

    public User getSeller() {
        return seller;
    }

    public void setSeller(User seller) {
        this.seller = seller;
    }

    public boolean isAvailable() {
        return isAvailable;
    }

    public void setAvailable(boolean available) {
        isAvailable = available;
    }

    public Order getOrder() {
        return order;
    }

    public void setOrder(Order order) {
        this.order = order;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Product product = (Product) o;
        return id == product.id &&
                price == product.price &&
                isAvailable == product.isAvailable &&
                Objects.equals(name, product.name) &&
                Objects.equals(description, product.description) &&
                Objects.equals(seller, product.seller);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, description, price, seller, isAvailable);
    }

    @Override
    public String toString() {
        return "Product{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", description='" + description + '\'' +
                ", price=" + price +
                ", seller=" + seller +
                ", isAvailable=" + isAvailable +
                '}';
    }
}

src/main/java/pl/codementors/finalstore/model/User.java
package pl.codementors.finalstore.model;

import javax.persistence.*;
import java.util.List;
import java.util.Objects;


/**
 * Entity class representing a User of our store.
 */
@Entity
@Table(name = "users", uniqueConstraints = @UniqueConstraint(columnNames = {"email", "nickname"}))
public class User {

    public enum Role {
        ADMIN,
        USER
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @Column
    private String name;

    @Column
    private String surname;

    @Column
    private String email;

    @Column
    private String nickname;

    @Column
    private String password;

    @Column
    private boolean isAccepted;

    @Column
    @Enumerated(EnumType.STRING)
    private Role role;

    @OneToMany(mappedBy = "customer", fetch = FetchType.EAGER)
    private List<Order> usersOrders;

    public User() {
    }

    public User(boolean isAccepted, Role role) {
        this.isAccepted = isAccepted;
        this.role = role;
    }

    public User(String name, String surname, String email, String nickname, String password, boolean isAccepted, Role role) {
        this.name = name;
        this.surname = surname;
        this.email = email;
        this.nickname = nickname;
        this.password = password;
        this.isAccepted = isAccepted;
        this.role = role;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public boolean isAccepted() {
        return isAccepted;
    }

    public void setAccepted(boolean accepted) {
        isAccepted = accepted;
    }

    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public List<Order> getUsersOrders() {
        return usersOrders;
    }

    public void setUsersOrders(List<Order> usersOrders) {
        this.usersOrders = usersOrders;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        User user = (User) o;
        return id == user.id &&
                isAccepted == user.isAccepted &&
                Objects.equals(name, user.name) &&
                Objects.equals(surname, user.surname) &&
                Objects.equals(email, user.email) &&
                Objects.equals(nickname, user.nickname) &&
                Objects.equals(password, user.password) &&
                role == user.role;
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, surname, email, nickname, password, isAccepted, role);
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", surname='" + surname + '\'' +
                ", email='" + email + '\'' +
                ", nickname='" + nickname + '\'' +
                ", password='" + password + '\'' +
                ", isAccepted=" + isAccepted +
                ", role=" + role +
                '}';
    }

    public static User createAnnonymousUser() {
        User user = new User();
        user.setName("Gal Anonim");
        user.setAccepted(false);
        return user;
    }
}

src/main/java/pl/codementors/finalstore/controller/LoginController.java
package pl.codementors.finalstore.controller;

import pl.codementors.finalstore.StoreDAO;
import pl.codementors.finalstore.model.User;

import javax.ejb.EJB;
import javax.inject.Inject;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.Optional;

/**
 * Servlet used to redirect user after success or failed login.
 */
@WebServlet("/login")
public class LoginController extends HttpServlet {

    /**
     * Bean EJB used to communicate with db.
     */
    @EJB
    private StoreDAO storeDAO;

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        String nickname = request.getParameter("j_username");
        String password = request.getParameter("j_password");
        Optional<User> userByNickAndPass = storeDAO.findUserByNickAndPass(nickname, password);

        if (userByNickAndPass.isPresent()) {
            request.login(nickname, password);
            request.getSession().setAttribute("user", userByNickAndPass.get());
            response.sendRedirect(request.getContextPath() + "/products.xhtml");
        } else {
            response.sendRedirect(request.getContextPath() + "/error.xhtml");
        }
    }


}

src/main/java/pl/codementors/finalstore/view/AccessController.java
package pl.codementors.finalstore.view;

import pl.codementors.finalstore.model.User;
import pl.codementors.finalstore.service.UserService;

import javax.ejb.EJB;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.io.Serializable;

/**
 * Access controller used to get currently logged user.
 */
@Named
@ViewScoped
public class AccessController implements Serializable {

    /**
     * Bean EJB used get user data.
     */
    @EJB
    private UserService service;

    /**
     * Method getting current user. Used to check if logged user is accepted.
     *
     * @return Currently logged user object.
     */
    public User getCurrentUser() {
        if (service.getCurrentlyLoggedUser().isPresent()) {
            return service.getCurrentlyLoggedUser().get();
        }
        return User.createAnnonymousUser();
    }
}

src/main/webapp/basket_view.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:p="http://primefaces.org/ui"
        template="/template.xhtml">
    <ui:define name="content">
        <h:dataTable value="#{basketView.productsInBasket}" var="product">
            <h:column>
                #{product.id}
            </h:column>
            <h:column>
                #{product.name}
            </h:column>
            <h:column>
                #{product.price}
            </h:column>
            <h:column>
                #{product.description}
            </h:column>
            <h:column>
                <h:form>
                    <h:commandButton value="#{msg.basRemove}" action="basket_view?faces-redirect=true"
                                     actionListener="#{basketView.removeProductFromBasket(product)}"/>
                </h:form>
            </h:column>
        </h:dataTable>
        <h:form>
            <h:panelGrid columns="2"
                         rendered="#{roleView.admin || (roleView.user &amp;&amp; mainView.currentUser.accepted)}">
                <p:outputLabel value="#{msg.basAddress}"/>
                <p:inputText disabled="#{!basketView.basketEmpty}" required="true" value="#{basketView.address}"/>
                <p:commandButton value="#{msg.basOrder}" actionListener="#{basketView.makeOrder}"
                                 action="products?faces-redirect=true" disabled="#{!basketView.basketEmpty}"/>
            </h:panelGrid>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/error.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:p="http://primefaces.org/ui"

        template="/template.xhtml">
    <ui:define name="content">
        <f:view>
            #{msg.err}
        </f:view>
    </ui:define>
</ui:composition>

src/main/webapp/main.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:p="http://primefaces.org/ui"

        template="/template.xhtml">
    <ui:define name="content">

        <f:view>
            <h:outputLabel value="Hello, this should not be here"/>
        </f:view>
    </ui:define>
</ui:composition>

src/main/webapp/my_orders.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:p="http://primefaces.org/ui"

        template="/template.xhtml">
    <ui:define name="content">
        <h:dataTable value="#{userOrders.userOrders}" var="order"
                     rendered="#{roleView.admin || (roleView.user &amp;&amp; mainView.currentUser.accepted)}">
            <h:column>
                <f:facet name="header">ID</f:facet>
                #{order.id}
            </h:column>
            <h:column>
                <f:facet name="header">#{msg.basAddress}</f:facet>
                #{order.adress}
            </h:column>
            <h:column>
                <f:facet name="header">#{msg.orProducts}</f:facet>
                <h:dataTable value="#{order.products}" var="product">
                    <h:column>
                        <f:facet name="header">#{msg.prName}</f:facet>
                        #{product.name}
                    </h:column>
                    <h:column>
                        <f:facet name="header">#{msg.prPrice}</f:facet>
                        #{product.price}
                    </h:column>
                    <h:column>
                        <f:facet name="header">#{msg.prSeller}</f:facet>
                        #{product.seller.nickname}
                    </h:column>
                </h:dataTable>
            </h:column>
        </h:dataTable>
    </ui:define>
</ui:composition>

src/main/webapp/my_products.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:p="http://primefaces.org/ui"

        template="/template.xhtml">
    <ui:define name="content">
        <h:dataTable value="#{userProducts.userProducts}" var="product"
                     rendered="#{roleView.admin || (roleView.user &amp;&amp; mainView.currentUser.accepted)}">
            <h:column>
                <f:facet name="header">ID</f:facet>
                #{product.id}
            </h:column>
            <h:column>
                <f:facet name="header">#{msg.prName}</f:facet>
                #{product.name}
            </h:column>
            <h:column>
                <f:facet name="header">#{msg.prPrice}</f:facet>
                #{product.price}
            </h:column>
            <h:column>
                <f:facet name="header">#{msg.prDescription}</f:facet>
                #{product.description}
            </h:column>
            <h:column>
                <h:form>
                    <h:commandButton value="#{msg.prDeleteOff}" action="my_products?faces-redirect=true"
                                     actionListener="#{userProducts.deleteProduct(product)}"
                                     rendered="#{product.available}"/>
                </h:form>
            </h:column>
            <h:column>
                <h:button outcome="product_edit" value="#{msg.prEdit}">
                    <f:param name="productId" value="#{product.id}"/>
                </h:button>
            </h:column>
        </h:dataTable>
        <p:button value="#{msg.prAdd}" rendered="#{roleView.admin || roleView.user}" outcome="new_offer">
            <f:param name="productId" value="0"/>
        </p:button>
    </ui:define>
</ui:composition>

src/main/webapp/new_offer.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:p="http://primefaces.org/ui"

        template="/template.xhtml">
    <ui:define name="content">
        <h:form>
            <h:panelGrid columns="2"
                         rendered="#{roleView.admin || (roleView.user &amp;&amp; mainView.currentUser.accepted)}">
                <h:outputLabel value="#{msg.prName}" for="name"/>
                <h:inputText id="name" value="#{newProduct.product.name}"/>
                <h:outputLabel value="#{msg.prPrice}" for="price"/>
                <h:inputText id="price" value="#{newProduct.product.price}"/>
                <h:outputLabel value="#{msg.prDescription}" for="description"/>
                <h:inputText id="description" value="#{newProduct.product.description}"/>
            </h:panelGrid>
            <h:commandButton actionListener="#{newProduct.saveProduct}" value="Save"
                             action="products.xhtml?faces-redirect=true"
                             rendered="#{roleView.admin || (roleView.user &amp;&amp; mainView.currentUser.accepted)}"/>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/product_edit.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:p="http://primefaces.org/ui"

        template="/template.xhtml">
    <f:metadata>
        <f:viewParam name="productId" value="#{productEdit.productId}"/>
    </f:metadata>
    <ui:define name="content">
        <h:form>
            <h:panelGrid columns="2" rendered="#{roleView.admin || (roleView.user &amp;&amp; mainView.currentUser.accepted
                &amp;&amp; productEdit.product.seller == mainView.currentUser)}">
                <f:facet name="header">
                    <h:outputText value="#{msg.prProduct}"/>
                </f:facet>
                <h:outputLabel value="#{msg.prName}" for="name"/>
                <h:inputText id="name" value="#{productEdit.product.name}"/>
                <h:outputLabel value="#{msg.prDescription}" for="description"/>
                <h:inputText id="description" value="#{productEdit.product.description}"/>
                <h:outputLabel value="#{msg.prPrice}" for="price"/>
                <h:inputText id="price" value="#{productEdit.product.price}"/>
                <h:outputLabel value="#{msg.prAvailability}" for="availability"/>
                <h:selectBooleanCheckbox value="#{productEdit.product.available}" id="availability"/>
            </h:panelGrid>
            <h:commandButton action="my_products?faces-redirect=true" actionListener="#{productEdit.updateProduct}"
                             value="#{msg.prSave}"
                             rendered="#{roleView.admin || (roleView.user &amp;&amp; mainView.currentUser.accepted
                             &amp;&amp; productEdit.product.seller == mainView.currentUser)}"/>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/products.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:p="http://primefaces.org/ui"

        template="/template.xhtml">
    <ui:define name="content">
        <h:button outcome="basket_view.xhtml" value="#{msg.prGoToBasket}"
                  rendered="#{roleView.admin || (roleView.user &amp;&amp; mainView.currentUser.accepted)}"
                  disabled="#{basketView.basketEmpty}"/>
        <h:dataTable value="#{productsList.productList}" var="product">
            <h:column>
                <f:facet name="header">ID</f:facet>
                #{product.id}
            </h:column>
            <h:column>
                <f:facet name="header">#{msg.prName}</f:facet>
                #{product.name}
            </h:column>
            <h:column>
                <f:facet name="header">#{msg.prPrice}</f:facet>
                #{product.price}
            </h:column>
            <h:column>
                <f:facet name="header">#{msg.prDescription}</f:facet>
                #{product.description}
            </h:column>
            <h:column rendered="#{roleView.admin || roleView.user}">
                <f:facet name="header">#{msg.prSeller}</f:facet>
                #{product.seller.name}
            </h:column>
            <h:column rendered="#{!roleView.admin &amp;&amp; !roleView.user}">
                <f:facet name="header">#{msg.prSeller}</f:facet>
                #{msg.prLogin}
            </h:column>
            <h:column>
                <h:form>
                    <p:commandButton value="#{msg.prAddToBasket}"
                                     rendered="#{roleView.admin || (roleView.user &amp;&amp; mainView.currentUser.accepted)}"
                                     actionListener="#{productsList.addProductToBasket(product)}"
                                     action="products?faces-redirect=true"
                                     disabled="#{productsList.addedToBasketOrNotAvailable(product)
                                     || productsList.isItMyOwnProduct(product)}"/>
                </h:form>
            </h:column>
        </h:dataTable>
        <h:form>
            <h:button value="#{msg.prAdd}"
                      rendered="#{roleView.admin || (roleView.user &amp;&amp; mainView.currentUser.accepted)}"
                      outcome="new_offer">
                <f:param name="productId" value="0"/>
            </h:button>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/template.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
    <title>FinalStore</title>
    <meta charset="UTF-8"/>
    <meta name="description" content="Random store!"/>
    <meta name="keywords" content="store, money"/>
    <meta name="author" content="Maciek"/>
    <meta name="author" content="Kuba"/>
    <meta name="author" content="Grzegorz"/>
    <h:outputStylesheet library="css" name="styles.css"/>
    <f:loadBundle var="msg" basename="view.messages"/>
</h:head>
<h:body styleClass="rootView">
    <h:outputStylesheet library="css" name="styles.css"/>

    <f:view>
        <h:panelGroup layout="block" styleClass="topDiv" id="panelId">
            <h:form>
                <p:commandLink value="#{mainView.loginButtonLabel}" ajax="true" update="panelId" styleClass="loginLink"
                               actionListener="#{mainView.logout}"/>
            </h:form>
            <p:link value="#{msg.register}" outcome="register.xhtml" styleClass="registerLink"/>
        </h:panelGroup>
        <h:panelGroup layout="block" styleClass="menuTop">

            <h:form>
                <p:tabMenu>
                    <p:menuitem action="users_list?faces-redirect=true" ajax="false" value="#{msg.usersList}"
                                rendered="#{roleView.admin}"/>
                    <p:menuitem action="products?faces-redirect=true" ajax="false" value="#{msg.avProducts}"/>
                    <p:menuitem outcome="user_edit?faces-redirect=true" value="#{msg.editUrDetails}"
                                rendered="#{!mainView.loggedInCheck}">
                        <f:param name="userId" value="#{mainView.currentUser.id}"/>
                    </p:menuitem>
                    <p:menuitem action="basket_view?faces-redirect=true" ajax="false" value="#{msg.myBasket}"
                                rendered="#{!mainView.loggedInCheck}"
                                disabled="#{!mainView.currentUser.accepted}"/>
                    <p:menuitem action="my_orders?faces-redirect=true" ajax="false" value="#{msg.myOrders}"
                                rendered="#{!mainView.loggedInCheck}"
                                disabled="#{!mainView.currentUser.accepted}"/>
                    <p:menuitem action="my_products?faces-redirect=true" value="#{msg.myProducts}"
                                rendered="#{!mainView.loggedInCheck}"
                                disabled="#{!mainView.currentUser.accepted}"/>
                </p:tabMenu>


            </h:form>
            <div style="text-align: center; color: #4f4f4f">
                <h:outputLabel rendered="#{roleView.user &amp;&amp; !mainView.currentUser.accepted}"
                               value="#{msg.accepted}"/>
            </div>
        </h:panelGroup>

        <h:panelGroup layout="block" styleClass="mainCenter">
            <p:layout style="width:1300px;min-height:700px;" styleClass="greyBack">
                <p:layoutUnit position="center" resizable="false" size="200" minSize="200" maxSize="300"
                              styleClass="greyBack">
                    <section>
                        <ui:insert name="content"/>
                    </section>
                </p:layoutUnit>
            </p:layout>
        </h:panelGroup>

    </f:view>
</h:body>
</html>

src/main/webapp/user_edit.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:p="http://primefaces.org/ui"

        template="/template.xhtml">
    <f:metadata>
        <f:viewParam name="userId" value="#{userEdit.userId}"/>
    </f:metadata>
    <ui:define name="content">
        <h:form>
            <h:panelGrid columns="2"
                         rendered="#{roleView.admin || (roleView.user &amp;&amp; userEdit.userId == mainView.currentUser.id)}">
                <f:facet name="header">
                    <h:outputText value="#{msg.usUser}"/>
                </f:facet>
                <h:outputLabel value="#{msg.usName}" for="name"/>
                <h:inputText id="name" value="#{userEdit.user.name}"/>
                <h:outputLabel value="#{msg.usSurname}" for="surname"/>
                <h:inputText id="surname" value="#{userEdit.user.surname}"/>
                <h:outputLabel value="Email" for="email"/>
                <h:inputText id="email" value="#{userEdit.user.email}"/>
                <h:outputLabel value="#{msg.usNickname}" for="nickname"/>
                <h:inputText id="nickname" value="#{userEdit.user.nickname}"/>
                <h:outputLabel for="password" value="#{msg.usPassword}"
                               rendered="#{roleView.user || (roleView.admin &amp;&amp; userEdit.userId == 0)
                               || (roleView.admin &amp;&amp; userEdit.userId == mainView.currentUser.id)}"/>
                <h:inputText id="password" value="#{userEdit.user.password}"
                             rendered="#{roleView.user || (roleView.admin &amp;&amp; userEdit.userId == 0)
                             || (roleView.admin &amp;&amp; userEdit.userId == mainView.currentUser.id)}"/>
                <h:outputLabel value="#{msg.usRole}:" for="role" rendered="#{roleView.admin}"/>
                <h:selectOneRadio id="role" value="#{userEdit.user.role}" rendered="#{roleView.admin}">
                    <f:selectItems value="#{userEdit.roles}"/>
                </h:selectOneRadio>
                <h:outputLabel value="#{msg.usAccept}" for="acceptance" rendered="#{roleView.admin}"/>
                <h:selectBooleanCheckbox value="#{userEdit.user.accepted}" id="acceptance"
                                         rendered="#{roleView.admin}"/>
            </h:panelGrid>
            <p:button action="user_edit?faces-redirect=true" actionListener="#{userEdit.saveUser}" value="#{msg.usSave}"
                      rendered="#{roleView.admin || (roleView.user &amp;&amp; userEdit.userId == mainView.currentUser.id)}">
                <f:param name="userId" value="#{mainView.currentUser.id}"/>
            </p:button>
        </h:form>
    </ui:define>
</ui:composition>